version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pymongo
    versions:
    - 3.11.2
  - dependency-name: jinja2
    versions:
    - 2.11.2
  - dependency-name: gunicorn
    versions:
    - 20.0.4
